### ISSUE TITLE
Could you help me?

### ISSUE THREAD

**Issue by z-ulrics** [dzalf/openQCM-GUI-Matlab#1]
I'm sorry to bother you so much. I have seen your OpenQCM project. Now I have an idea that if the computer is connected to two Arduino at the same time, and the data is read at the same time and displayed in one interface. If possible, could you please tell me how the programming needs to be changed? Thank you.

**Comment by dzalf** [comment]
Hi. My apologies for the late reply. This GUI was only intended to be used for 1 single device connected to the serial port. In order to add more devices, major modifications would have to be implemented. For instance, create a Class that defines an openQCM board with all of its properties and instantiate as many devices as you need. You would also need to modify the live plotting function. This is something that I have been wishing to accomplish, however I would not implement this in Matlab. I would move to C++ or Python. Hope this helps

**Comment by z-ulrics** [comment]
> 你好。我为迟到的回复道歉。此 GUI 仅用于连接到串行端口的 1 个单个设备。为了添加更多设备，必须进行重大修改。例如，创建一个定义 openQCM 板及其所有属性的类，并根据需要实例化任意数量的设备。您还需要修改实时绘图功能。这是我一直希望完成的事情，但是我不会在 Matlab 中实现它。我会转向 C++ 或 Python。希望这可以帮助

Could we achieve by adjust code in java?

**Comment by dzalf** [comment]
Technically, you can use any language. Java is a good candidate as Matlab is based on Java.

I am closing this issue as I have provided a response to your original request.
